export * from './base.module';
export * from './base.component';
export * from './tela-principal';
export * from './cadastropessoastela';
export * from './cadastro';
export * from './listarpessoas';
export * from './tarefas';
export * from './shared';
export * from './sources';
